"""add videos

Revision ID: 1085caaee13e
Revises: 8058f3924e6e
Create Date: 2026-02-23 21:31:59.977365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1085caaee13e'
down_revision = '8058f3924e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('rel_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index('ix_videos_academia_alumno', ['academia_id', 'alumno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_academia_id'), ['academia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_alumno_id'), ['alumno_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_alumno_id'))
        batch_op.drop_index(batch_op.f('ix_videos_academia_id'))
        batch_op.drop_index('ix_videos_academia_alumno')

    op.drop_table('videos')
    # ### end Alembic commands ###
