"""add poomsae and video patron

Revision ID: 3d27ae744a19
Revises: 7286ecad4a14
Create Date: 2026-02-24 21:41:56.275862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d27ae744a19'
down_revision = '7286ecad4a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poomsaes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poomsaes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poomsaes_codigo'), ['codigo'], unique=True)

    op.create_table('videos_patron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('poomsae_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['poomsae_id'], ['poomsaes.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academia_id', 'poomsae_id', 'activo', name='uq_patron_acad_poom_activo')
    )
    with op.batch_alter_table('videos_patron', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_patron_academia_id'), ['academia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_patron_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_patron_poomsae_id'), ['poomsae_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_patron_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_patron', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_patron_video_id'))
        batch_op.drop_index(batch_op.f('ix_videos_patron_poomsae_id'))
        batch_op.drop_index(batch_op.f('ix_videos_patron_activo'))
        batch_op.drop_index(batch_op.f('ix_videos_patron_academia_id'))

    op.drop_table('videos_patron')
    with op.batch_alter_table('poomsaes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poomsaes_codigo'))

    op.drop_table('poomsaes')
    # ### end Alembic commands ###
