"""add poomsae_id to videos

Revision ID: 588f11d7a661
Revises: 3d27ae744a19
Create Date: 2026-02-26 11:33:28.503140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '588f11d7a661'
down_revision = '3d27ae744a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poomsae_id', sa.Integer(), nullable=True))
        batch_op.alter_column('mime_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('size_bytes',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_videos_academia_alumno'))
        batch_op.create_index(batch_op.f('ix_videos_poomsae_id'), ['poomsae_id'], unique=False)
        batch_op.create_foreign_key(None, 'poomsaes', ['poomsae_id'], ['id'])
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_videos_poomsae_id'))
        batch_op.create_index(batch_op.f('ix_videos_academia_alumno'), ['academia_id', 'alumno_id'], unique=False)
        batch_op.alter_column('size_bytes',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('mime_type',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               existing_nullable=True)
        batch_op.drop_column('poomsae_id')

    # ### end Alembic commands ###
