"""add evaluaciones and evaluacion_items

Revision ID: 6571865a42f7
Revises: f9c0794d4480
Create Date: 2026-02-24 09:42:46.665427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6571865a42f7'
down_revision = 'f9c0794d4480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('juez_user_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['juez_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluaciones_academia_id'), ['academia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluaciones_juez_user_id'), ['juez_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluaciones_video_id'), ['video_id'], unique=False)

    op.create_table('evaluacion_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('criterio_codigo', sa.String(length=50), nullable=False),
    sa.Column('criterio_nombre', sa.String(length=120), nullable=False),
    sa.Column('puntaje', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_puntaje', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluacion_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluacion_items_evaluacion_id'), ['evaluacion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluacion_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluacion_items_evaluacion_id'))

    op.drop_table('evaluacion_items')
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluaciones_video_id'))
        batch_op.drop_index(batch_op.f('ix_evaluaciones_juez_user_id'))
        batch_op.drop_index(batch_op.f('ix_evaluaciones_academia_id'))

    op.drop_table('evaluaciones')
    # ### end Alembic commands ###
