"""analisis_videos

Revision ID: 7286ecad4a14
Revises: 6571865a42f7
Create Date: 2026-02-24 14:14:29.645107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7286ecad4a14'
down_revision = '6571865a42f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('score_total', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_estabilidad', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('score_ritmo', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('error_msg', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analisis_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analisis_videos_academia_id'), ['academia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analisis_videos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_analisis_videos_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analisis_videos_video_id'))
        batch_op.drop_index(batch_op.f('ix_analisis_videos_estado'))
        batch_op.drop_index(batch_op.f('ix_analisis_videos_academia_id'))

    op.drop_table('analisis_videos')
    # ### end Alembic commands ###
