"""add alumnos

Revision ID: 8058f3924e6e
Revises: f9c9723c12e5
Create Date: 2026-02-23 21:06:58.064452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8058f3924e6e'
down_revision = 'f9c9723c12e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('cinturon', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.create_index('ix_alumnos_academia_apellidos', ['academia_id', 'apellidos'], unique=False)
        batch_op.create_index(batch_op.f('ix_alumnos_academia_id'), ['academia_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alumnos_academia_id'))
        batch_op.drop_index('ix_alumnos_academia_apellidos')

    op.drop_table('alumnos')
    # ### end Alembic commands ###
